Repository DhanushNehru/HarmonyCode, pull requests merged in 2023-10, with the labels that each got.

#11 Added Social Share feature
  .gitignore
  components/Footer.js
  package-lock.json
  package.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#13 twitter link added
  components/Footer.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#18 Added badges to the Readme
  README.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#20 Added social icons such as github twitter linkdin instagram
  components/Footer.js
  components/GoogleSignIn.js
  components/Header.js
  package-lock.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#25 Fixed #24 where Twitter(X) logo was not visible on desktop
  components/Footer.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#30 docs: Improved and clarified Gitpod setup instructions
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted
